"use client";

import Image from "next/image";
import { useRouter } from "next/navigation";
import { useEffect } from "react";
import './2fa-login.css';




export default function TwoFactorMessage() {
  const router = useRouter();

  const handleSkip = () => {
    window.location.href = '/menu';
  };

    
  useEffect(() => {
    const handlePopState = () => {
      console.log("Navigated back or forward");
      // Adicione lógica aqui, como recarregar a página ou atualizar o estado
      window.location.reload(); // Opcional: recarrega a página
    };
  
    window.addEventListener("popstate", handlePopState);
  
    return () => {
      window.removeEventListener("popstate", handlePopState);
    };
  }, []);

  return (
    <div className="container">
          <div className="logo">
            <Image src="/images/logo.png" alt="LockBox Logo" width={60} height={60} />
          </div>
          
          <h1>Enter Confirmation Code</h1>
          <p>Enter the 6-digit code generated by</p>
          <p>Google Authenticator.</p>

          <div className="code-inputs">
              {Array.from({ length: 6 }).map((_, index) => (
                <input
                key={index}
                type="text"
                maxLength={1}
                onInput={(e) => {
                  const target = e.target as HTMLInputElement;
                  if (target.value.length === 1 && target.nextElementSibling) {
                  (target.nextElementSibling as HTMLInputElement).focus();
                  }
                }}
                onKeyDown={(e) => {
                  const target = e.target as HTMLInputElement;
                  if (e.key === "Backspace" && !target.value && target.previousElementSibling) {
                  (target.previousElementSibling as HTMLInputElement).focus();
                  }
                }}
                required
                />
              ))}
              </div>

          <div className= "two-buttons">
            <button className="Now" onClick={handleSkip}>Next</button>
          </div>
    </div>
  );
}
